rules/numbers-test.yml, rules/numbers.yml, spectral.yml
s,numeric,integer, in a buggy rule
See #14
=> Fix: #14. Integer require format.

rules/metadata-test.yml, rules/metadata.yml, spectral.yml
=> Fix: #11. Check ToS and contact.

package-lock.json
=> Bump jquery 3.5.1

public/js/index.js
this would fix https://github.com/teamdigitale/api-oas-checker/issues/23
=> added url oas_url filling on window load via url get param

README.md
=> Thanks Paolo Falomo.

publiccode.yaml
=> Add publiccode.yaml

Makefile, rules/metadata-test.snapshot, rules/numbers-test.snapshot, rules/patch-test.snapshot, rules/problem-test.snapshot, rules/ratelimit-test.snapshot, test-ruleset.sh
=> Improve tests

rules/casing-test.snapshot, rules/casing-test.yml, rules/casing.yml, rules/metadata.yml, test-ruleset.sh
Adds casing support for:
- paths
- headers
Fixes: #20
=> Fix: #20. Casing support for headers and paths.

Makefile, rules/problem-test.snapshot, rules/problem-test.yml, rules/problem.yml, rules/schemas-test.snapshot, rules/schemas-test.yml, rules/schemas.yml, test-ruleset.sh
- Fixes #34 improves problemjson support
- Fixes #37 splitting schema tests on another file
=> Improve mediatype support (problem+json and other)

.circleci/config.yml, test-ruleset.sh
=> Add tests in CI

README.md
=> Reference github action.

rules/merge-yaml, rules/oas3only-test.snapshot, rules/oas3only-test.yml, rules/oas3only.yml, test-ruleset.sh
=> Forbid Swagger 2.

README.md, docker-compose.yml
=> Test with docker

index.html
Loads yaml.js from codemirror, thus supporting syntax highlighting.
=> Fix: #48. Yaml syntax highlight.

README.en.md
Closes https://github.com/teamdigitale/api-oas-checker/issues/21
=> README.md translated to English

rules/headers-test.snapshot, rules/headers-test.yml, rules/headers.yml, test-ruleset.sh
=> Fix: #53. Add no x-headers rule with some exceptions.

Makefile, test-ruleset.sh
=> Support multiple testdirs

README.en.md, README.md
=> Remove broken link

public/js/index.js
Fixes tab behavior
see https://codemirror.net/doc/manual.html#command_indentMore
=> Fix "tab" behavior without breaking indentation.

package-lock.json, package.json
=> Bump: spectral 5.6.0

README.md
Adds a readme badge in English
=> Readme english badge

rules/headers.yml, rules/tests/headers-test.snapshot, rules/tests/headers-test.yml
Signals when OAS-forbidden headers are declared.
=> Signal forbidden headers.

rules/metadata.yml, rules/tests/metadata-test.snapshot, rules/tests/metadata-test.yml
=> Rule: use semantic versioning

index.html, public/js/index.js
Entire validation process is covered by a simple spinner which will tell to user the something is going on under the hood.
Fixes: #2
=> Validation process covered by a spinner

index.html, public/js/index.js
- fixes a missing export
- add jsonschema support
=> Fix missing export. Add jsonschema.

index.html, public/js/index.js
=> Add documentation in textarea

index.html, public/js/index.js
=> Remove unuseful label.

index.html, package-lock.json, package.json
=> Bump spectral 5.7.1

security/array.yml, security/numbers.yml, security/string.yml, security/tests/array-test.snapshot, security/tests/numbers-test.snapshot, security/tests/string-test.snapshot, security/tests/string-test.yml
fixes #80 using `defined` function
=> Fix: #80. Improved ruleset.

rules/problem.yml, rules/tests/problem-test.snapshot
=> Updated correct links with text

Makefile
=> Fix makefile on MacOS

Dockerfile, Makefile, docker-compose.yml
Pins node version in docker files.
Fixes #96
=> Pin node version in docker and Fix Makefile

rules/casing.yml, rules/headers.yml, rules/metadata.yml, rules/numbers.yml, rules/patch.yml, rules/paths.yml, rules/ratelimit.yml, rules/tests/headers-test.snapshot, rules/tests/metadata-test.snapshot, rules/tests/patch-test.snapshot, test-ruleset.sh
=> Improve rules description

Makefile
- generate doc.html file list
- builds them with a mock `touch` command
- clean them
=> boilerplate to generate doc.html files

rules/tests/casing-test.snapshot, rules/tests/headers-test.snapshot, rules/tests/metadata-test.snapshot, rules/tests/numbers-test.snapshot, rules/tests/oas3only-test.snapshot, rules/tests/patch-test.snapshot, rules/tests/paths-test.snapshot, rules/tests/problem-test.snapshot, rules/tests/ratelimit-test.snapshot, rules/tests/schemas-test.snapshot, security/tests/array-test.snapshot, security/tests/numbers-test.snapshot, security/tests/string-test.snapshot
=> Update snapshot for spectral 5.8

src/components/ValidationResultItem.js, src/components/ValidationSummary.js, src/scss/bootstrap-italia-custom.scss
=> fix: badges style in the summary section

ruleset_doc_generator.mjs
Auto-links RFC in markdown. It would be great to have it in the modal window too.
=> Auto-link RFCs.

rules/headers.yml, rules/patch.yml, rules/paths.yml, rules/problem.yml, rules/ratelimit.yml, rules/tests/problem-test.snapshot, security/array.yml, security/objects.yml, security/securitySchemes.yml, security/string.yml, security/tests/objects-test.snapshot, security/tests/objects-test.yml, security/tests/securitySchemes-test.snapshot, security/tests/securitySchemes-test.yml, security/tests/string-test.snapshot, security/tests/string-test.yml
This is WIP until switch to 5.8 is completed.
=> Improve security description

security/securitySchemes.yml, security/tests/securitySchemes-test.snapshot, security/tests/securitySchemes-test.yml, test-ruleset.sh
=> Fix: #140. Check JWT best practices.

rules/https.yml, rules/metadata.yml, rules/tests/https-test.yml, rules/tests/metadata-test.snapshot
checks in-operation servers for https
=> Fix: #143. In-operation servers must use https.

package.json, yarn.lock
Fixes [this](https://github.com/advisories/GHSA-9qmh-276g-x5pj) security vulnerability
=> chore: fix security alert

rules/cache-control.yml, rules/casing.yml, rules/problem.yml, rules/ratelimit.yml, rules/rules-template.yml.template, rules/tests/cache-control-test.snapshot, rules/tests/https-test.snapshot, test-ruleset.sh
- fixes typos
- improve problem description
- improve comment
=> Fix rules typos.

README.md, docker-compose.yml
- Adds instruction for using rulesets in vscode
- add a docker service for developing on machines without node
=> Add IDE instructions.

security/securitySchemes.yml, security/tests/securitySchemes-test.snapshot, security/tests/securitySchemes-test.yml
-  forbids implicit and password grant types in oauth2 as they are now considered insecure
=> Forbid implicit and password grant types in oauth2. See #158

test-ruleset.sh
- more readable test output, ignoring changes in line numbers
=> Improve test output visualization.

package.json, yarn.lock
bumps minor version of libraries
=> chore: bump minor version of libraries

publiccode.yml
=> Align publiccode.yaml

rules/patch.yml, rules/tests/patch-test.snapshot, rules/tests/patch-test.yml
=> Fix: #307. No GET with body.

rules/casing.yml, rules/tests/casing-test.snapshot, rules/tests/casing-test.yml
- hint: Schemas in CamelCase.
cc: @vlauciani
=> Fix: #413. Schemas should be CamelCase.

rules/patch.yml, rules/tests/patch-test.snapshot, rules/tests/patch-test.yml
=> Fix: #427. Add PATCH needs body

package.json
=> Release 0.3.3

README.en.md, README.md
=> Fix: #438. Versioned rulesets.

security/parameters.yml, security/tests/parameters-test.snapshot, security/tests/parameters-test.yml
- add checks for passwords and secrets in URL (query or path parameters).
=> Don't send secrets in URLs. See #442.

security/securitySchemes_insecure.yml, security/tests/securitySchemes_insecure-test.snapshot, security/tests/securitySchemes_insecure-test.yml
- hints on api keys
- error on insecure auth mechanisms
=> Fix: #422. Forbid insecure schemes and cookie/query apiKeys.

security/array.yml, security/numbers.yml, security/objects.yml, security/securitySchemes.yml, security/securitySchemes_insecure.yml, security/string.yml, security/tests/array-test.snapshot, security/tests/numbers-test.snapshot, security/tests/objects-test.snapshot, security/tests/securitySchemes-test.snapshot, security/tests/securitySchemes_insecure-test.snapshot, security/tests/string-test.snapshot
- prefix with `sec-`
- move required stuff in `rules'
See #440
=> Prefix with sec-. See #440.

package.json, public/errorfile.yaml
- add an error file to showcase API OAS Checker functionalities.
=> Fix: #443. Add errorfile.

rules/cache-control.yml, rules/patch.yml, rules/ratelimit.yml
Fixed some typos in the rulesets found by codespellchecker
=> fix-typos in rulesets

rules/cache-control.yml, rules/casing.yml, rules/headers.yml, rules/numbers.yml, rules/oauth2.yml, rules/patch.yml, rules/paths.yml, rules/problem.yml, rules/ratelimit.yml, rules/schemas.yml, rules/secrets-parameters.yml, security/array.yml, security/numbers.yml, security/objects.yml, security/securitySchemes.yml, security/securitySchemes_insecure.yml, security/string.yml
=> Fix jsonpath expressions 

rules/tests/numbers-test.snapshot, rules/tests/numbers-test.yml
=> Fix typos.

rules/patch.yml, rules/schemas.yml, rules/tests/patch-test.snapshot, rules/tests/patch-test.yml, rules/tests/schemas-test.snapshot, rules/tests/schemas-test.yml
- checks  that json-patch mediatype is array
- minor fixes
=> json-patch mediatype is array

src/components/ValidationController.js, src/redux/reducers/documentReducer.js
supports passing files via URL
=> Support url param.

public/oas3-completion.schema.json, src/components/Editor.js
uses jsonschema to autocomplete keywords
=> Minimal completion features based on OAS3 spec.

src/components/Editor.js, src/components/ValidationResultItem.js, src/spectral/spectral_utils.js, src/utils.mjs
Shows hints with a different color.
=> Fix: #528. Show hints with a different color.

rules/naming.yml, rules/tests/naming-test.snapshot, rules/tests/naming-test.yml
- checks for recommended variable names
=> Fix: #523. Basic naming test.

src/components/ValidationResultItem.js
- larger modal for rule descriptions
- Fixes #147
=> Fix: #147. Large modal for rule description.

src/index.js
=> fix: switch to react createroot #589

rules/naming.yml, rules/tests/naming-test.snapshot, rules/tests/naming-test.yml
=> Fix: 596. No method names in operationId.

rules/problem.yml, rules/tests/problem-test.snapshot
- fixes problem+json checks
Fix: #626.
=> Fix: #626. Add problem-json hint.

README.en.md, README.md
- clarifies that we don't want to deploy servers.
=> Readme clarifications
